# Generated by Django 2.2.14 on 2021-11-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_ratingreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingreview',
            name='review',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
