# Generated by Django 2.2.14 on 2021-11-28 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211128_1018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatingReview',
        ),
    ]
